require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # —
  # ActionDispatch::HostAuthorization (Rails 8) nega pedidos com Host não listado —
  # típico: Safari/telemóvel em `http://IP-da-LAN:3000` ou hostname `.local` / Docker Desktop.
  # Sem isto aparece erro «Blocked hosts» ou página sem conteúdo útil em alguns cenários.
  # Hosts ou regex extra: variável opcional `.env`: DEV_ALLOWED_HOSTS=meu.hostname,172.31.10.50
  %w[host.docker.internal].each { |host| config.hosts << host }
  config.hosts << /\.ts\.net\z/i # Tailscale MagicDNS (*.tailscale.net / *.ts.net)
  config.hosts << /\.tailscale\.net\z/i
  # CGNAT típico do Tailscale: 100.64.0.0/10 (100.64.x.x … 100.127.x.x)
  config.hosts << /\A100\.(?:6[4-9]|[7-9]\d|1[01]\d|12[0-7])(?:\.[0-9]{1,3}){2}\z/i
  config.hosts << /\A192\.168\.\d{1,3}\.\d{1,3}\z/i
  config.hosts << /\A10\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/i
  config.hosts << /\A172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}\z/i # 172.16.0.0–172.31.255.255
  config.hosts << /\.local\z/i
  ENV.fetch("DEV_ALLOWED_HOSTS", "").split(",").each do |host|
    host = host.strip
    next if host.blank?

    config.hosts << host
  end

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
